# Numpy - Cheat Sheet



In [ ]:
import numpy as np

##Create numpy array from Python list

In [ ]:
list1 = list(range(10))
list1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
arr1 = np.array(list1)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##Shape (dimension) of array

In [ ]:
arr1.shape

(10,)

In [ ]:
mat1 = arr1.reshape((2,5))
mat1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
mat1.shape

(2, 5)

##Common Mathematics Fomular

In [ ]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.mean(arr1)

4.5

In [ ]:
np.std(arr1)

2.8722813232690143

In [ ]:
np.sin(arr1)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

##Boardcasting Operation

In [ ]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr2 = arr1 * 2
arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr3 = arr1 + arr2
arr3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

##Indexing and Selection

In [ ]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr1[0:5]

array([0, 1, 2, 3, 4])

In [ ]:
mat2 = np.arange(0, 25).reshape((5,5))
mat2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
mat2[0]

array([0, 1, 2, 3, 4])

In [ ]:
mat2[0, 1:4]

array([1, 2, 3])

In [ ]:
mat2[0:3, 1:4]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [ ]:
mat2[:, 0:2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16],
       [20, 21]])